export { captureScreenshot } from './modules/browser/capture-screenshot.ts'
export type { CaptureOptions } from './modules/browser/capture-screenshot.ts'
export { resolveOutputPath } from './modules/output/resolve-output-path.ts'
export { resolvePreset } from './modules/preset/resolve-preset.ts'
export type { PresetConfig } from './modules/preset/resolve-preset.ts'
